"""Fixed expenses t bug

Revision ID: bc0ddd569033
Revises: 8944d2a34c48
Create Date: 2021-06-07 19:00:28.254168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0ddd569033'
down_revision = '8944d2a34c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expenses_tripId_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'trips', ['tripId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_tripId_fkey', 'expenses', 'expenses', ['tripId'], ['id'])
    # ### end Alembic commands ###
